---

- name: Ensures {{ destFolder }} dir exists
  file:
    path: "{{ destFolder }}"
    state: directory

- name: Copy files
  copy:
    src: "{{ item }}"
    remote_src: no
    dest: "{{ destFolder }}"
  loop:
    - "chart"

- name: Register deployed count chart
  shell: helm ls | grep {{ releaseName }} | wc -l
  register: deployed

- name: Install fluentd
  shell: |
    helm install \
     --name {{ releaseName }} \
     --set elasticsearch.host={{ elasticsearch.host }},elasticsearch.port={{ elasticsearch.port }},elasticsearch.scheme={{ elasticsearch.scheme }},elasticsearch.ssl.verify={{ elasticsearch.ssl.verify }} \
     --wait {{ destFolder }}/chart
  when: deployed.stdout == "0"
